"""
SchemeSaathi - Verified Government Schemes Knowledgebase & Seed Registry
Contains comprehensive schema for Central and State government schemes in India.
All URLs strictly resolve to official (.gov.in / .nic.in) domains.
"""

VERIFIED_SCHEMES_SEED = [
    {
        "id": "pm-kisan",
        "title": "PM-Kisan Samman Nidhi Yojana",
        "short_desc": "Income support of ₹6,000 per year in three equal installments of ₹2,000 directly into bank accounts of landholding farmer families.",
        "detailed_desc": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) is a Central Sector Scheme with 100% funding from Government of India. Under the scheme, an income support of ₹6,000 per year is provided to all landholding farmer families across the country in three equal installments of ₹2,000 each every 4 months directly into their Aadhaar-seeded bank accounts via Direct Benefit Transfer (DBT).",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "department": "Department of Agriculture and Farmers Welfare",
        "category": "Agriculture & Farmers",
        "target_beneficiary": "Small and Marginal Landholding Farmers",
        "min_age": 18,
        "max_age": 100,
        "gender_criteria": "ALL",
        "max_income": 300000,
        "social_category": ["ALL"],
        "occupation": ["Farmer", "Agriculture Worker", "Landowner"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": True,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Must possess cultivable landholding in revenue records; Institutional landholders and income tax payees are excluded.",
        "benefit_amount": "₹6,000 / year",
        "benefit_type": "Direct Cash Transfer (DBT)",
        "benefit_details": "₹2,000 disbursed every 4 months via Direct Benefit Transfer (DBT) into Aadhaar-seeded bank account.",
        "required_documents": [
            "Aadhaar Card",
            "Bank Account / Passbook with DBT Seeding",
            "Land Records / 7/12 Extract / RoR",
            "Citizenship / Domicile Proof"
        ],
        "application_mode": "Online (pmkisan.gov.in) / CSC / State Agriculture Dept",
        "application_process": "1. Visit pmkisan.gov.in and click 'New Farmer Registration'. 2. Enter Aadhaar and mobile number to verify OTP. 3. Enter land details (Khasra/Khatauni number). 4. Local Patwari/Revenue officer verifies land records. 5. State nodal officer approves application for DBT.",
        "official_url": "https://pmkisan.gov.in",
        "info_url": "https://pmkisan.gov.in",
        "official_domain": "pmkisan.gov.in",
        "grievance_portal": "https://pmkisan.gov.in/Grievance.aspx",
        "helpline": "155261 / 011-24300606",
        "start_date": "2019-02-01",
        "deadline": "Open Year-Round (19th Installment KYC by 30-Nov-2026)",
        "deadline_days_left": 95,
        "renewal_requirements": "Periodic biometric / facial e-KYC on PM-Kisan portal",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-15",
        "source_authority": "Ministry of Agriculture & Farmers Welfare, GoI",
        "verification_status": "VERIFIED",
        "priority_weight": 95
    },
    {
        "id": "post-matric-scholarship",
        "title": "Post-Matric Scholarship for SC / ST / OBC / EWS Students",
        "short_desc": "Financial assistance for higher secondary and post-matriculation / tertiary studies covering tuition, maintenance allowances, and book grants.",
        "detailed_desc": "Post-Matric Scholarship is a Centrally Sponsored Scheme implemented through State Governments and UT Administrations. It aims to substantially increase Gross Enrolment Ratio (GER) of students from economically weaker and marginalized backgrounds in higher education by providing full fee reimbursement and monthly living stipends.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Social Justice and Empowerment",
        "department": "Department of Higher Education & Social Welfare",
        "category": "Education & Scholarships",
        "target_beneficiary": "Students enrolled in Class 11, 12, ITI, Diploma, Degree, or Post-Graduate courses",
        "min_age": 15,
        "max_age": 35,
        "gender_criteria": "ALL",
        "max_income": 250000,
        "social_category": ["SC", "ST", "OBC", "EWS"],
        "occupation": ["Student"],
        "area_criteria": "ALL",
        "education_criteria": "10th Passed / Enrolled in Recognized Higher Ed Institution",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": True,
        "has_girl_child": False,
        "other_conditions": "Must have passed previous qualifying examination with at least 50% marks; Not receiving any other centrally funded scholarship.",
        "benefit_amount": "₹12,000 to ₹45,000 / year",
        "benefit_type": "Tuition Fee Waiver + Monthly Maintenance Allowance",
        "benefit_details": "Full non-refundable tuition reimbursement plus up to ₹1,200/month living stipend directly into student bank account.",
        "required_documents": [
            "Aadhaar Card",
            "Income Certificate",
            "Caste Certificate & Validity",
            "10th / 12th Marksheet",
            "College / School Admission Receipt & Bonafide",
            "Bank Account / Passbook with DBT Seeding",
            "Domicile Certificate"
        ],
        "application_mode": "Online via National Scholarship Portal (NSP)",
        "application_process": "1. Register on scholarships.gov.in with Aadhaar. 2. Select Post-Matric Scholarship under relevant ministry. 3. Upload marksheets, fee receipt, and income certificate. 4. Institution verifies student records online (Level 1). 5. District Social Welfare Officer sanctions scholarship (Level 2).",
        "official_url": "https://scholarships.gov.in",
        "info_url": "https://scholarships.gov.in",
        "official_domain": "scholarships.gov.in",
        "grievance_portal": "https://scholarships.gov.in/fresh/newstdRegfrmInstruction",
        "helpline": "0120-6619540 / helpdesk@nsp.gov.in",
        "start_date": "2006-04-01",
        "deadline": "31-Oct-2026 (Apply Early)",
        "deadline_days_left": 65,
        "renewal_requirements": "Annual renewal with latest year passing marksheet and updated income certificate",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-10",
        "source_authority": "Ministry of Social Justice and Empowerment / Ministry of Tribal Affairs",
        "verification_status": "VERIFIED",
        "priority_weight": 98
    },
    {
        "id": "pm-awas-yojana-gramin",
        "title": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        "short_desc": "Financial grant of ₹1.20 Lakh to ₹1.30 Lakh to eligible rural homeless or kutcha house households for constructing permanent pucca homes.",
        "detailed_desc": "PMAY-G aims to provide a pucca house with basic amenities to all rural houseless households and households living in kutcha and dilapidated houses. Beneficiaries are identified using housing deprivation parameters in the Socio-Economic and Caste Census (SECC) and verified by the Gram Sabha.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Rural Development",
        "department": "Rural Housing Division",
        "category": "Housing & Infrastructure",
        "target_beneficiary": "Rural homeless or families living in zero/one/two-room kutcha houses",
        "min_age": 18,
        "max_age": 100,
        "gender_criteria": "ALL",
        "max_income": 200000,
        "social_category": ["ALL"],
        "occupation": ["Farmer", "Agricultural Laborer", "Artisan", "Rural Worker", "Unemployed"],
        "area_criteria": "Rural",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Household must not own a motor vehicle, mechanized agricultural equipment, or a pucca house in India.",
        "benefit_amount": "₹1,20,000 (Plain) / ₹1,30,000 (Hilly/NE States)",
        "benefit_type": "Direct Housing Grant + MGNREGA Labor Component",
        "benefit_details": "Grant released in 3 geo-tagged construction stages + 90 days MGNREGA wages + ₹12,000 for SBM toilet construction.",
        "required_documents": [
            "Aadhaar Card",
            "Bank Account / Passbook with DBT Seeding",
            "Ration Card (BPL / AAY)",
            "Income Certificate",
            "Land / House Site Ownership Document or Gram Panchayat NOC"
        ],
        "application_mode": "Gram Panchayat / AwaasApp / Block Development Office",
        "application_process": "1. Name inclusion in Gram Panchayat Awaas+ priority list. 2. Geo-tagging of existing kutcha site by Block official. 3. Sanction letter generation on pmayg.nic.in. 4. Release of 1st installment (₹40,000) for plinth construction. 5. Subsequent installments after physical verification.",
        "official_url": "https://pmayg.nic.in",
        "info_url": "https://pmayg.nic.in",
        "official_domain": "pmayg.nic.in",
        "grievance_portal": "https://pmayg.nic.in/netiay/grievance.aspx",
        "helpline": "1800-11-6446 / support-pmayg@gov.in",
        "start_date": "2016-11-20",
        "deadline": "Open Scheme (PMAY-G 2.0 Allocation Phase)",
        "deadline_days_left": 120,
        "renewal_requirements": "Not applicable (One-time asset creation grant)",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-01",
        "source_authority": "Ministry of Rural Development, GoI",
        "verification_status": "VERIFIED",
        "priority_weight": 90
    },
    {
        "id": "ayushman-bharat-pmjay",
        "title": "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
        "short_desc": "Cashless health insurance cover of ₹5,00,000 per family per year for secondary and tertiary healthcare across 27,000+ empanelled hospitals.",
        "detailed_desc": "PM-JAY is the world's largest government-funded healthcare assurance scheme. It provides a health cover of ₹5 Lakh per family per year for secondary and tertiary care hospitalization to over 12 crore poor and vulnerable families (approximately 55 crore beneficiaries). Coverage includes pre-hospitalization, medicines, diagnostics, surgery, and post-hospitalization care.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Health and Family Welfare",
        "department": "National Health Authority (NHA)",
        "category": "Healthcare & Wellness",
        "target_beneficiary": "Vulnerable and low-income families identified by deprivation criteria in SECC/NFSA databases",
        "min_age": 0,
        "max_age": 120,
        "gender_criteria": "ALL",
        "max_income": 300000,
        "social_category": ["ALL"],
        "occupation": ["All Categories"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Family must be listed in SECC 2011 deprivation categories or active NFSA Ration Card database.",
        "benefit_amount": "₹5,00,000 / family / year",
        "benefit_type": "100% Cashless Inpatient Hospitalization Cover",
        "benefit_details": "Covers 1,949 medical procedures, ICU, oncology, cardiology, neurosurgery with zero out-of-pocket expenditure.",
        "required_documents": [
            "Aadhaar Card",
            "Ration Card (BPL / AAY)",
            "Income Certificate"
        ],
        "application_mode": "Online (beneficiary.nha.gov.in) / Ayushman Mitra at any Empanelled Hospital / CSC",
        "application_process": "1. Visit beneficiary.nha.gov.in or nearest hospital Ayushman Kiosk. 2. Search family name using Aadhaar or Ration Card number. 3. Complete instant e-KYC using Aadhaar OTP or biometric scan. 4. Download Ayushman Bharat Card immediately with unique PMJAY ID.",
        "official_url": "https://beneficiary.nha.gov.in",
        "info_url": "https://pmjay.gov.in",
        "official_domain": "beneficiary.nha.gov.in",
        "grievance_portal": "https://cgrms.pmjay.gov.in",
        "helpline": "14555 / 1800-111-565",
        "start_date": "2018-09-23",
        "deadline": "Open Scheme (Continuous Card Generation)",
        "deadline_days_left": 365,
        "renewal_requirements": "Automatic annual wallet renewal on 1st April",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-14",
        "source_authority": "National Health Authority, MoHFW",
        "verification_status": "VERIFIED",
        "priority_weight": 92
    },
    {
        "id": "pm-mudra-yojana",
        "title": "Pradhan Mantri MUDRA Yojana (PMMY)",
        "short_desc": "Collateral-free micro-enterprise loans up to ₹20 Lakh across Shishu, Kishore, Tarun, and Tarun Plus categories for small business ventures.",
        "detailed_desc": "PMMY provides collateral-free loans to micro and small enterprises in manufacturing, trading, and service sectors. Divided into: Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 Lakh), Tarun (₹5 Lakh to ₹10 Lakh), and Tarun Plus (₹10 Lakh to ₹20 Lakh for entrepreneurs who have repaid previous loans).",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Finance",
        "department": "Department of Financial Services",
        "category": "Business & MSME",
        "target_beneficiary": "Non-Corporate, Non-Farm Small/Micro Enterprises, Shopkeepers, Artisans, Small Manufacturers",
        "min_age": 18,
        "max_age": 65,
        "gender_criteria": "ALL",
        "max_income": 1500000,
        "social_category": ["ALL"],
        "occupation": ["Self-Employed", "Entrepreneur", "Street Vendor", "Artisan", "Trader"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Applicant must not be a defaulter to any bank or financial institution; Must have a viable non-farm business project plan.",
        "benefit_amount": "Up to ₹20 Lakh Collateral-Free Business Credit",
        "benefit_type": "Institutional Working Capital / Term Loan",
        "benefit_details": "Zero collateral, subsidized interest rates via Credit Guarantee Fund for Micro Units (CGFMU).",
        "required_documents": [
            "Aadhaar Card",
            "PAN Card",
            "Bank Account / Passbook with DBT Seeding",
            "Udyam MSME Registration Certificate"
        ],
        "application_mode": "Online via Udyamimitra Portal (udyamimitra.in) or any Public/Private Sector Bank",
        "application_process": "1. Prepare simple business projection / machinery quotation. 2. Apply on udyamimitra.in or visit nearest bank branch. 3. Submit proof of identity, address, and business registration. 4. Bank sanctions loan under MUDRA scheme without collateral.",
        "official_url": "https://www.mudra.org.in",
        "info_url": "https://www.mudra.org.in",
        "official_domain": "mudra.org.in",
        "grievance_portal": "https://pgportal.gov.in",
        "helpline": "1800-180-1111 / 1800-11-0001",
        "start_date": "2015-04-08",
        "deadline": "Open Year-Round",
        "deadline_days_left": 365,
        "renewal_requirements": "Annual review for working capital limits (Cash Credit / Overdraft)",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-12",
        "source_authority": "Department of Financial Services, Ministry of Finance",
        "verification_status": "VERIFIED",
        "priority_weight": 86
    },
    {
        "id": "pm-svanidhi",
        "title": "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
        "short_desc": "Affordable working capital collateral-free micro-loans of ₹10,000, ₹20,000, and ₹50,000 with 7% interest subsidy for urban street vendors.",
        "detailed_desc": "PM SVANidhi is a special micro-credit facility for street vendors affected during economic disruptions. It provides collateral-free working capital loan of ₹10,000 (1st tranche). On timely repayment, vendors are eligible for 2nd tranche of ₹20,000 and 3rd tranche of ₹50,000 with 7% interest subsidy and cashback of up to ₹1,200/year on digital transactions.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Housing and Urban Affairs",
        "department": "Urban Livelihoods Division",
        "category": "Business & MSME",
        "target_beneficiary": "Urban street vendors, hawkers, thelawalas engaged in vending on or before March 2020",
        "min_age": 18,
        "max_age": 70,
        "gender_criteria": "ALL",
        "max_income": 300000,
        "social_category": ["ALL"],
        "occupation": ["Street Vendor", "Hawker", "Self-Employed"],
        "area_criteria": "Urban",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Must possess Certificate of Vending (CoV) / Identity Card issued by Urban Local Body (ULB) or Letter of Recommendation (LoR).",
        "benefit_amount": "₹10,000 → ₹20,000 → ₹50,000 Working Capital Loan",
        "benefit_type": "Subsidized Micro Credit + 7% Interest Subsidy + Digital Cashback",
        "benefit_details": "7% interest subvention credited quarterly into bank account; Up to ₹100/month cashback on UPI sales.",
        "required_documents": [
            "Aadhaar Card",
            "Vending Certificate / Urban Local Body Identity Card",
            "Bank Account / Passbook with DBT Seeding"
        ],
        "application_mode": "Online via pmsvanidhi.mohua.gov.in / PM SVANidhi Mobile App / ULB Town Vending Committee",
        "application_process": "1. Verify Vending Certificate or obtain Letter of Recommendation from local Nagar Nigam/Palika. 2. Apply on pmsvanidhi.mohua.gov.in. 3. Select preferred lending bank. 4. Direct loan disbursal into bank account within 7 days.",
        "official_url": "https://pmsvanidhi.mohua.gov.in",
        "info_url": "https://pmsvanidhi.mohua.gov.in",
        "official_domain": "pmsvanidhi.mohua.gov.in",
        "grievance_portal": "https://pmsvanidhi.mohua.gov.in/Home/ContactUs",
        "helpline": "1800-11-1979",
        "start_date": "2020-06-01",
        "deadline": "Open Scheme (Phase 3 Expansion)",
        "deadline_days_left": 180,
        "renewal_requirements": "Upgrade to next tranche upon complete repayment of previous tranche",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-08",
        "source_authority": "Ministry of Housing and Urban Affairs, GoI",
        "verification_status": "VERIFIED",
        "priority_weight": 88
    },
    {
        "id": "sukanya-samriddhi",
        "title": "Sukanya Samriddhi Yojana (SSY)",
        "short_desc": "Government-backed high-interest savings scheme (8.2% p.a.) with full Section 80C tax exemption for building girl child education & marriage corpus.",
        "detailed_desc": "Sukanya Samriddhi Account is a government-backed small deposit scheme under the Beti Bachao Beti Padhao campaign. It offers the highest sovereign interest rate (currently 8.2% per annum compounded annually) with triple tax benefits (EEE - Exempt on deposit, interest, and maturity).",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Finance",
        "department": "National Savings Institute / Department of Posts",
        "category": "Women & Child Welfare",
        "target_beneficiary": "Parents or legal guardians of girl children below 10 years of age (maximum 2 girls per family)",
        "min_age": 0,
        "max_age": 10,
        "gender_criteria": "Female",
        "max_income": 5000000,
        "social_category": ["ALL"],
        "occupation": ["All Categories"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": True,
        "other_conditions": "Account can be opened from girl child birth up to age 10; Minimum annual deposit ₹250, maximum ₹1.5 Lakh.",
        "benefit_amount": "8.2% Annual Sovereign Interest + Triple Tax Exemption (EEE)",
        "benefit_type": "Long-Term Guaranteed Wealth & Education Security",
        "benefit_details": "Deposit period is 15 years; Account matures in 21 years or on marriage after age 18; 50% partial withdrawal for higher education after Class 10.",
        "required_documents": [
            "Aadhaar Card",
            "Birth Certificate of Girl Child",
            "Citizenship / Domicile Proof"
        ],
        "application_mode": "Any Post Office (India Post) or authorized Public/Private Bank branch",
        "application_process": "1. Fill Sukanya Samriddhi Account Opening Form at Post Office or Bank. 2. Attach child's birth certificate and guardian's Aadhaar/PAN. 3. Deposit initial opening amount (minimum ₹250). 4. Receive SSY Passbook.",
        "official_url": "https://www.indiapost.gov.in",
        "info_url": "https://www.nsiindia.gov.in",
        "official_domain": "indiapost.gov.in",
        "grievance_portal": "https://www.indiapost.gov.in/VAS/Pages/CustomerSupport/Grievances.aspx",
        "helpline": "1800-266-6868",
        "start_date": "2015-01-22",
        "deadline": "Open Scheme (Girl child age < 10 years)",
        "deadline_days_left": 365,
        "renewal_requirements": "Minimum deposit of ₹250 per financial year to prevent account default",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-05",
        "source_authority": "Department of Economic Affairs, Ministry of Finance",
        "verification_status": "VERIFIED",
        "priority_weight": 89
    },
    {
        "id": "pm-vishwakarma",
        "title": "PM Vishwakarma Scheme",
        "short_desc": "Holistic support for traditional artisans & craftspeople: PM Vishwakarma Certificate, ₹15,000 modern toolkit incentive, skill training, and 5% subsidized loans up to ₹3 Lakh.",
        "detailed_desc": "PM Vishwakarma provides end-to-end holistic support to traditional artisans and craftspersons across 18 trades (Carpenter, Blacksmith, Goldsmith, Potter, Sculptor, Cobbler, Tailor, Barber, etc.). Includes official PM Vishwakarma ID card, 5-7 days basic skill training with ₹500/day stipend, ₹15,000 digital e-voucher for modern toolkits, and collateral-free credit (₹1 Lakh 1st tranche, ₹2 Lakh 2nd tranche) at a concessional interest rate of 5%.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "department": "Ministry of Skill Development & MSME",
        "category": "Artisans & Crafts",
        "target_beneficiary": "Traditional artisans and craftspeople working with hands and tools in 18 specified trades",
        "min_age": 18,
        "max_age": 75,
        "gender_criteria": "ALL",
        "max_income": 400000,
        "social_category": ["ALL"],
        "occupation": ["Artisan", "Craftsperson", "Carpenter", "Blacksmith", "Potter", "Tailor", "Barber", "Cobbler"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Must be actively practicing one of the 18 family-based traditional trades; Only one member per family is eligible; Must not have availed PMEGP/Mudra loans in last 5 years.",
        "benefit_amount": "₹15,000 Toolkit Grant + ₹3 Lakh Loan @ 5% Interest + ₹500/day Stipend",
        "benefit_type": "Skill Training + Toolkit Incentive + Subsidized Enterprise Credit",
        "benefit_details": "Digital PM Vishwakarma Certificate + ₹15,000 modern tool e-voucher + up to ₹3 Lakh enterprise credit at 5% interest rate.",
        "required_documents": [
            "Aadhaar Card",
            "Bank Account / Passbook with DBT Seeding",
            "Ration Card (BPL / AAY)"
        ],
        "application_mode": "Online biometric registration via Common Services Centers (CSC) on pmvishwakarma.gov.in",
        "application_process": "1. Visit nearest CSC with Aadhaar and bank details. 2. Complete biometric authentication. 3. Gram Panchayat / ULB verifies traditional trade practice (Level 1). 4. District Implementation Committee screening (Level 2). 5. State/National Committee approval (Level 3).",
        "official_url": "https://pmvishwakarma.gov.in",
        "info_url": "https://pmvishwakarma.gov.in",
        "official_domain": "pmvishwakarma.gov.in",
        "grievance_portal": "https://pmvishwakarma.gov.in/ContactUs",
        "helpline": "1800-267-7777 / 011-23061500",
        "start_date": "2023-09-17",
        "deadline": "Open Year-Round",
        "deadline_days_left": 365,
        "renewal_requirements": "Completion of advanced skill training to unlock 2nd credit tranche of ₹2 Lakh",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-16",
        "source_authority": "Ministry of MSME, Government of India",
        "verification_status": "VERIFIED",
        "priority_weight": 94
    },
    {
        "id": "naps-apprenticeship",
        "title": "National Apprenticeship Promotion Scheme (NAPS)",
        "short_desc": "On-the-job industrial skill training for youth with government stipend support of 25% of prescribed stipend up to ₹1,500/month directly into bank accounts.",
        "detailed_desc": "NAPS promotes apprenticeship training across industries by reimbursing 25% of prescribed stipend up to a maximum of ₹1,500 per month per apprentice directly to the apprentice's bank account via DBT on behalf of participating enterprises.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Skill Development and Entrepreneurship",
        "department": "National Skill Development Corporation (NSDC)",
        "category": "Skill Development & Employment",
        "target_beneficiary": "Youth, ITI pass-outs, Graduates, Diploma holders seeking industry on-the-job training",
        "min_age": 14,
        "max_age": 35,
        "gender_criteria": "ALL",
        "max_income": 500000,
        "social_category": ["ALL"],
        "occupation": ["Student", "Unemployed", "Job Seeker", "Graduate"],
        "area_criteria": "ALL",
        "education_criteria": "5th / 8th / 10th / 12th / ITI / Diploma / Graduate",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Must register on Apprenticeship India portal and contract with an empanelled establishment.",
        "benefit_amount": "₹1,500 / month government co-pay (Total stipend ₹8,000-₹15,000)",
        "benefit_type": "Monthly Stipend Subsidy + National Trade Certificate",
        "benefit_details": "Direct practical training with top private/public employers; recognized government certification upon completion.",
        "required_documents": [
            "Aadhaar Card",
            "10th / 12th Marksheet",
            "Bank Account / Passbook with DBT Seeding"
        ],
        "application_mode": "Online Apprenticeship Portal (apprenticeshipindia.gov.in)",
        "application_process": "1. Create Candidate Profile on apprenticeshipindia.gov.in. 2. Complete e-KYC using Aadhaar. 3. Search and apply for open apprenticeship opportunities in your district. 4. Sign digital apprenticeship contract with company.",
        "official_url": "https://www.apprenticeshipindia.gov.in",
        "info_url": "https://www.apprenticeshipindia.gov.in",
        "official_domain": "apprenticeshipindia.gov.in",
        "grievance_portal": "https://www.apprenticeshipindia.gov.in/contact-us",
        "helpline": "011-47451600",
        "start_date": "2016-08-19",
        "deadline": "Open Year-Round (Quarterly Hiring Batches)",
        "deadline_days_left": 45,
        "renewal_requirements": "Periodic assessment and attendance logging on apprenticeship portal",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-11",
        "source_authority": "MSDE / National Skill Development Corporation",
        "verification_status": "VERIFIED",
        "priority_weight": 87
    },
    {
        "id": "pm-surya-ghar",
        "title": "PM Surya Ghar: Muft Bijli Yojana",
        "short_desc": "Direct capital subsidy of up to ₹78,000 for installing grid-connected solar rooftop systems, providing up to 300 units of free electricity monthly.",
        "detailed_desc": "PM Surya Ghar: Muft Bijli Yojana aims to provide free electricity up to 300 units every month to 1 crore households across India through rooftop solar installations. Subsidies include ₹30,000 for 1 kW, ₹60,000 for 2 kW, and ₹78,000 for 3 kW or higher systems, with low-interest collateral-free loans at 7% from commercial banks.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of New and Renewable Energy",
        "department": "National Rooftop Solar Division",
        "category": "Energy & Sustainability",
        "target_beneficiary": "Residential households with suitable roof space and active electricity connection",
        "min_age": 18,
        "max_age": 100,
        "gender_criteria": "ALL",
        "max_income": 10000000,
        "social_category": ["ALL"],
        "occupation": ["All Categories"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Applicant household must have an active residential electricity connection and suitable rooftop space for solar panel installation.",
        "benefit_amount": "Up to ₹78,000 Direct DBT Subsidy + 300 Units Free Power / month",
        "benefit_type": "Direct Capital Subsidy + Net Metering Power Bill Savings",
        "benefit_details": "Subsidy credited directly into bank account within 30 days of DISCOM inspection and net-meter commissioning.",
        "required_documents": [
            "Aadhaar Card",
            "Electricity Bill",
            "Bank Account / Passbook with DBT Seeding"
        ],
        "application_mode": "Online National Portal for Rooftop Solar (pmsuryaghar.gov.in)",
        "application_process": "1. Register on pmsuryaghar.gov.in with state DISCOM consumer number. 2. Submit rooftop solar application. 3. Select registered solar vendor for installation. 4. DISCOM installs net-meter and generates commissioning certificate. 5. Direct subsidy release.",
        "official_url": "https://pmsuryaghar.gov.in",
        "info_url": "https://pmsuryaghar.gov.in",
        "official_domain": "pmsuryaghar.gov.in",
        "grievance_portal": "https://pmsuryaghar.gov.in",
        "helpline": "15555 / 1800-180-3333",
        "start_date": "2024-02-15",
        "deadline": "Open Scheme",
        "deadline_days_left": 365,
        "renewal_requirements": "Periodic inverter and net-meter health check by DISCOM",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-16",
        "source_authority": "Ministry of New and Renewable Energy, GoI",
        "verification_status": "VERIFIED",
        "priority_weight": 91
    },
    {
        "id": "atal-pension-yojana",
        "title": "Atal Pension Yojana (APY)",
        "short_desc": "Government-backed guaranteed monthly pension of ₹1,000 to ₹5,000 starting at age 60 for citizens working in the unorganized sector.",
        "detailed_desc": "APY is a pension scheme focused on all citizens in the unorganised sector. It guarantees a minimum monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000 or ₹5,000 per month from the age of 60 years depending on the monthly contribution, with spouse pension and nominee corpus return.",
        "level": "Central",
        "state": "All India",
        "ministry": "Ministry of Finance",
        "department": "Pension Fund Regulatory and Development Authority (PFRDA)",
        "category": "Pension & Social Security",
        "target_beneficiary": "All Indian citizens aged between 18 and 40 years, especially unorganized workers",
        "min_age": 18,
        "max_age": 40,
        "gender_criteria": "ALL",
        "max_income": 800000,
        "social_category": ["ALL"],
        "occupation": ["Unorganized Worker", "Self-Employed", "Artisan", "Laborer", "Farmer"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Applicant must be an Indian citizen aged 18-40; Must not be an income tax payer as per latest APY rules.",
        "benefit_amount": "Guaranteed ₹1,000 to ₹5,000 / month Lifelong Pension",
        "benefit_type": "Guaranteed Sovereign Retirement Pension",
        "benefit_details": "Lifelong pension after age 60. Same pension to spouse on subscriber death; Full accumulated corpus (up to ₹8.5 Lakh) returned to nominee.",
        "required_documents": [
            "Aadhaar Card",
            "Bank Account / Passbook with DBT Seeding"
        ],
        "application_mode": "Online via NetBanking / Any Commercial Bank / Post Office Branch",
        "application_process": "1. Visit bank where savings account is held. 2. Fill APY registration form with nominee details. 3. Set up monthly auto-debit for contribution. 4. Receive PRAN (Permanent Retirement Account Number).",
        "official_url": "https://www.npscra.nsdl.co.in",
        "info_url": "https://www.pfrda.org.in",
        "official_domain": "npscra.nsdl.co.in",
        "grievance_portal": "https://cra-nsdl.com/CRA/grievanceEntry.do",
        "helpline": "1800-110-069",
        "start_date": "2015-05-09",
        "deadline": "Open (Age eligibility 18-40 years)",
        "deadline_days_left": 365,
        "renewal_requirements": "Maintain active bank balance for automatic monthly contribution deduction",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-10",
        "source_authority": "PFRDA / Ministry of Finance",
        "verification_status": "VERIFIED",
        "priority_weight": 85
    },
    {
        "id": "mh-ladki-bahin-yojana",
        "title": "Mukhyamantri Majhi Ladki Bahin Yojana",
        "short_desc": "Monthly financial assistance of ₹1,500 directly transferred into bank accounts of eligible women aged 21-65 years in Maharashtra.",
        "detailed_desc": "Mukhyamantri Majhi Ladki Bahin Yojana is a flagship Maharashtra State Government welfare initiative aimed at economic empowerment, health, and nutritional security of women. It provides ₹1,500 every month (₹18,000 annually) directly into the Aadhaar-linked bank accounts of married, widowed, divorced, or single women.",
        "level": "State",
        "state": "Maharashtra",
        "ministry": "Government of Maharashtra",
        "department": "Women and Child Development Department, Maharashtra",
        "category": "Women & Child Welfare",
        "target_beneficiary": "Women aged 21 to 65 years residing in Maharashtra from low-income families",
        "min_age": 21,
        "max_age": 65,
        "gender_criteria": "Female",
        "max_income": 250000,
        "social_category": ["ALL"],
        "occupation": ["All Categories", "Homemaker", "Self-Employed", "Worker"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Applicant must be a permanent resident of Maharashtra with family annual income under ₹2.50 Lakh; Family should not have a 4-wheeler (except tractor) or income tax payee.",
        "benefit_amount": "₹1,500 / month (₹18,000 / year)",
        "benefit_type": "Direct Cash Transfer (DBT)",
        "benefit_details": "₹1,500 monthly credit directly into Aadhaar-seeded bank account via DBT on the 15th of every month.",
        "required_documents": [
            "Aadhaar Card",
            "Domicile Certificate",
            "Income Certificate",
            "Ration Card (BPL / AAY)",
            "Bank Account / Passbook with DBT Seeding"
        ],
        "application_mode": "Online via Nari Shakti Doot App / MahaDBT / Anganwadi / Setu Suvidha Kendra",
        "application_process": "1. Download Nari Shakti Doot App or visit local Anganwadi/Setu Kendra. 2. Enter Aadhaar and complete OTP verification. 3. Upload Domicile Certificate, Ration Card, and bank details. 4. Ward/Gram Panchayat scrutiny and approval.",
        "official_url": "https://ladakibahin.maharashtra.gov.in",
        "info_url": "https://ladakibahin.maharashtra.gov.in",
        "official_domain": "ladakibahin.maharashtra.gov.in",
        "grievance_portal": "https://grievances.maharashtra.gov.in",
        "helpline": "181 / 022-22025251",
        "start_date": "2024-07-01",
        "deadline": "Open Scheme (Continuous Enrolment)",
        "deadline_days_left": 365,
        "renewal_requirements": "Annual self-declaration of income and family status",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-16",
        "source_authority": "Women & Child Development Department, Govt of Maharashtra",
        "verification_status": "VERIFIED",
        "priority_weight": 96
    },
    {
        "id": "mh-mahadbt-shahu-maharaj",
        "title": "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (EBC)",
        "short_desc": "50% tuition and exam fee reimbursement for Economically Backward Class (EBC) students pursuing higher professional degrees in Maharashtra.",
        "detailed_desc": "Implemented by the Directorate of Technical Education and Higher Education, Government of Maharashtra, this scheme reimburses 50% of the tuition fee and examination fee for students admitted through CAP rounds in engineering, medical, pharmacy, management, architecture, and general degree courses whose family annual income is under ₹8 Lakh.",
        "level": "State",
        "state": "Maharashtra",
        "ministry": "Government of Maharashtra",
        "department": "Higher and Technical Education Department, Maharashtra",
        "category": "Education & Scholarships",
        "target_beneficiary": "EBC / General category students admitted to recognized diploma, degree, or post-graduate courses in Maharashtra",
        "min_age": 16,
        "max_age": 30,
        "gender_criteria": "ALL",
        "max_income": 800000,
        "social_category": ["ALL", "General", "EWS"],
        "occupation": ["Student"],
        "area_criteria": "ALL",
        "education_criteria": "12th Passed / Diploma Passed / Enrolled in Higher Ed",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": True,
        "has_girl_child": False,
        "other_conditions": "Admission must be through Centralized Admission Process (CAP); Maximum 2 beneficiaries per family; Attendance above 75%.",
        "benefit_amount": "50% Tuition Fee + 50% Exam Fee Waiver (Up to ₹50,000 / year)",
        "benefit_type": "Direct Fee Reimbursement to College / Student DBT",
        "benefit_details": "Tuition fee waiver credited directly to institution; Examination fee component transferred to student bank account.",
        "required_documents": [
            "Aadhaar Card",
            "Domicile Certificate",
            "Income Certificate",
            "10th / 12th Marksheet",
            "College / School Admission Receipt & Bonafide",
            "Bank Account / Passbook with DBT Seeding"
        ],
        "application_mode": "Online via MahaDBT Portal (mahadbt.maharashtra.gov.in)",
        "application_process": "1. Create applicant profile on mahadbt.maharashtra.gov.in with Aadhaar. 2. Select Department of Higher/Technical Education. 3. Upload CAP allotment letter, income certificate (under ₹8L), and fee receipt. 4. Institute and Joint Director verification.",
        "official_url": "https://mahadbt.maharashtra.gov.in",
        "info_url": "https://mahadbt.maharashtra.gov.in",
        "official_domain": "mahadbt.maharashtra.gov.in",
        "grievance_portal": "https://mahadbt.maharashtra.gov.in/Grievance",
        "helpline": "022-49150800",
        "start_date": "2018-06-01",
        "deadline": "30-Nov-2026",
        "deadline_days_left": 95,
        "renewal_requirements": "Annual renewal with marksheets showing promotion to next academic year",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-14",
        "source_authority": "Higher & Technical Education Department, Govt of Maharashtra",
        "verification_status": "VERIFIED",
        "priority_weight": 93
    },
    {
        "id": "mh-sanjay-gandhi-niradhar",
        "title": "Sanjay Gandhi Niradhar Anudan Yojana",
        "short_desc": "Monthly pension of ₹1,500 for destitute persons, widows, divorced women, abandoned wives, and persons with severe disabilities in Maharashtra.",
        "detailed_desc": "Sanjay Gandhi Niradhar Anudan Yojana provides financial support of ₹1,500 per month to destitute persons (aged 65+ without family support), widows, orphan children, persons with 40% or more disability, and individuals suffering from major severe medical conditions whose annual family income is under ₹50,000 (relaxed to ₹1,00,000 in specific categories).",
        "level": "State",
        "state": "Maharashtra",
        "ministry": "Government of Maharashtra",
        "department": "Social Justice and Special Assistance Department, Maharashtra",
        "category": "Social Welfare & Disability",
        "target_beneficiary": "Destitute elderly, widows, orphans, and persons with 40%+ disability in Maharashtra",
        "min_age": 18,
        "max_age": 120,
        "gender_criteria": "ALL",
        "max_income": 100000,
        "social_category": ["ALL"],
        "occupation": ["Unemployed", "Destitute", "Disabled"],
        "area_criteria": "ALL",
        "education_criteria": "None",
        "disability_criteria": "None",
        "requires_land": False,
        "requires_student": False,
        "has_girl_child": False,
        "other_conditions": "Applicant must be a resident of Maharashtra for at least 15 years; Income must not exceed ₹50,000/year (or ₹1,00,000 for families with 2+ beneficiaries).",
        "benefit_amount": "₹1,500 / month (₹18,000 / year)",
        "benefit_type": "Monthly Social Security Pension",
        "benefit_details": "₹1,500 deposited directly into bank account every month through the Tehsildar Social Welfare Office.",
        "required_documents": [
            "Aadhaar Card",
            "Domicile Certificate",
            "Income Certificate",
            "Bank Account / Passbook with DBT Seeding"
        ],
        "application_mode": "Offline at Tehsil Office / Setu Suvidha Kendra / Online on Aaple Sarkar (aaplesarkar.mahaonline.gov.in)",
        "application_process": "1. Submit application form at local Tehsil office or online on Aaple Sarkar. 2. Attach Age/Disability/Death certificate of spouse and 15-year Domicile proof. 3. Tehsildar Committee scrutinizes and sanctions monthly pension.",
        "official_url": "https://sjsa.maharashtra.gov.in",
        "info_url": "https://aaplesarkar.mahaonline.gov.in",
        "official_domain": "sjsa.maharashtra.gov.in",
        "grievance_portal": "https://aaplesarkar.mahaonline.gov.in/en/Grievance",
        "helpline": "1800-120-8040",
        "start_date": "1980-10-02",
        "deadline": "Open Year-Round",
        "deadline_days_left": 365,
        "renewal_requirements": "Annual life certificate (Jeevan Pramaan) verification in November",
        "scheme_status": "ACTIVE",
        "last_verified_date": "2026-08-07",
        "source_authority": "Social Justice & Special Assistance Dept, Govt of Maharashtra",
        "verification_status": "VERIFIED",
        "priority_weight": 86
    }
,
{
    "id": "stand-up-india",
    "title": "Stand-Up India Scheme",
    "short_desc": "Bank loans between ₹10 Lakh and ₹1 Crore for setting up greenfield enterprises by SC, ST, or Women entrepreneurs in manufacturing, services, or agri-allied sectors.",
    "detailed_desc": "Stand-Up India Scheme facilitates bank loans between ₹10 Lakh and ₹1 Crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield (first-time) enterprise.",
    "level": "Central",
    "state": "All India",
    "ministry": "Ministry of Finance",
    "department": "Department of Financial Services / SIDBI",
    "category": "Business, MSME & Entrepreneurship",
    "target_beneficiary": "SC, ST and Women entrepreneurs establishing new commercial enterprises",
    "min_age": 18,
    "max_age": 70,
    "gender_criteria": "ALL",
    "max_income": 10000000,
    "social_category": [
        "SC",
        "ST",
        "ALL_IF_WOMEN"
    ],
    "occupation": [
        "Entrepreneur",
        "Self-Employed",
        "Business Owner"
    ],
    "area_criteria": "ALL",
    "education_criteria": "None",
    "disability_criteria": "None",
    "requires_land": False,
    "requires_student": False,
    "has_girl_child": False,
    "other_conditions": "Enterprise must be greenfield (first time venture); In case of non-individual enterprises, 51% shareholding must be held by SC/ST or woman entrepreneur.",
    "benefit_amount": "₹10 Lakh to ₹1 Crore Bank Credit (Composite Loan)",
    "benefit_type": "Greenfield Business Term Loan + Working Capital",
    "benefit_details": "Composite loan covering up to 85% of project cost with repayment period up to 7 years and 18-month moratorium.",
    "required_documents": [
        "Aadhaar Card",
        "PAN Card",
        "Caste Certificate & Validity",
        "Bank Account / Passbook with DBT Seeding",
        "Detailed Project Report (DPR) / Greenfield Business Plan"
    ],
    "application_mode": "Online via Stand-Up India Portal (standupmitra.in) or directly through Scheduled Commercial Banks",
    "application_process": "1. Register on standupmitra.in. 2. Submit Detailed Project Report (DPR). 3. Select Handholding Agency or Lead Bank. 4. SIDBI / Bank processes credit appraisal and disburses composite loan.",
    "official_url": "https://www.standupmitra.in",
    "info_url": "https://www.standupmitra.in",
    "official_domain": "standupmitra.in",
    "grievance_portal": "https://www.standupmitra.in/Home/ContactUs",
    "helpline": "1800-180-1111",
    "start_date": "2016-04-05",
    "deadline": "Extended up to 2027",
    "deadline_days_left": 365,
    "renewal_requirements": "Regular submission of audited financial statements and working capital stock statements",
    "scheme_status": "ACTIVE",
    "last_verified_date": "2026-08-02",
    "source_authority": "Small Industries Development Bank of India (SIDBI) / MoF",
    "verification_status": "VERIFIED",
    "priority_weight": 84
},
{
    "id": "test-dynamic-scheme-101",
    "title": "National Green Energy Rooftop Solar Scheme",
    "short_desc": "Subsidies up to ₹78,000 for installing grid-connected solar panels on residential rooftops.",
    "detailed_desc": "",
    "level": "Central",
    "state": "All India",
    "ministry": "Ministry of New and Renewable Energy",
    "department": "",
    "category": "Energy & Sustainability",
    "target_beneficiary": "All Citizens",
    "min_age": 0,
    "max_age": 120,
    "gender_criteria": "ALL",
    "max_income": 9999999,
    "social_category": [
        "ALL"
    ],
    "occupation": [
        "All"
    ],
    "area_criteria": "ALL",
    "education_criteria": "None",
    "disability_criteria": "None",
    "requires_land": False,
    "requires_student": False,
    "has_girl_child": False,
    "other_conditions": "",
    "benefit_amount": "₹78,000 Direct Subsidy",
    "benefit_type": "Welfare Grant",
    "benefit_details": "",
    "required_documents": [
        "Aadhaar Card",
        "Electricity Bill",
        "Bank Account / Passbook with DBT Seeding"
    ],
    "application_mode": "Online",
    "application_process": "",
    "official_url": "https://pmsuryaghar.gov.in",
    "info_url": "",
    "official_domain": "pmsuryaghar.gov.in",
    "grievance_portal": "",
    "helpline": "",
    "start_date": "",
    "deadline": "Open",
    "deadline_days_left": 180,
    "renewal_requirements": "",
    "scheme_status": "ACTIVE",
    "last_verified_date": "2026-08-31",
    "source_authority": "Government Department",
    "verification_status": "VERIFIED",
    "priority_weight": 88
}
]

def get_seed_schemes():
    return VERIFIED_SCHEMES_SEED
